select 'Connected successfully!' as message
  from dual;

create table users (
   id       number
      generated by default as identity,
   username varchar2(50) not null,
   password varchar2(100) not null,
   email    varchar2(100),
   primary key ( id )
);

insert into users (
   username,
   password,
   email
) values ( 'admin',
           'admin123',
           'admin@example.com' );

select *
  from users;

create table dashboard_cards (
   id         varchar2(50) primary key,
   icon_class varchar2(100),
   title_key  varchar2(100),
   stat       varchar2(20),
   desc_key   varchar2(100)
);

insert into dashboard_cards (
   id,
   icon_class,
   title_key,
   stat,
   desc_key
) values ( 'sales',
           'FaChartBar text-blue-400',
           'label:sales_performance',
           '$12,430',
           'label:track_sales_performance' );
insert into dashboard_cards (
   id,
   icon_class,
   title_key,
   stat,
   desc_key
) values ( 'users',
           'FaUsers text-green-400',
           'label:new_users',
           '1,280',
           'label:user_acquisition' );
insert into dashboard_cards (
   id,
   icon_class,
   title_key,
   stat,
   desc_key
) values ( 'orders',
           'FaShoppingCart text-orange-400',
           'label:total_orders',
           '845',
           'label:orders_overview' );
insert into dashboard_cards (
   id,
   icon_class,
   title_key,
   stat,
   desc_key
) values ( 'sales2',
           'FaChartBar text-blue-400',
           'label:sales_performance',
           '$12,430',
           'label:track_sales_performance' );

select *
  from dashboard_cards;

create table top_products (
   id            number
      generated always as identity
   primary key,
   product_label varchar2(100)
);

insert into top_products ( product_label ) values ( 'label:product_a' );
insert into top_products ( product_label ) values ( 'label:product_b' );
insert into top_products ( product_label ) values ( 'label:product_c' );

select *
  from top_products;

create table sales_overview_datasets (
   dataset_id       number
      generated by default on null as identity
   primary key,
   label            varchar2(100),
   background_color varchar2(20),
   border_color     varchar2(20)
);

insert into sales_overview_datasets (
   label,
   background_color,
   border_color
) values ( 'Sales Overview 2024',
           '#FF9E00',
           '#FF9E00' );
insert into sales_overview_datasets (
   label,
   background_color,
   border_color
) values ( 'Sales Overview 2025',
           '#36A2EB',
           '#36A2EB' );

select *
  from sales_overview_datasets;

create table sales_overview_values (
   dataset_id  number,
   month_label varchar2(20),
   value       number,
   foreign key ( dataset_id )
      references sales_overview_datasets ( dataset_id )
);

insert into sales_overview_values (
   dataset_id,
   month_label,
   value
) values ( 1,
           'January',
           30 );
insert into sales_overview_values (
   dataset_id,
   month_label,
   value
) values ( 1,
           'February',
           50 );
insert into sales_overview_values (
   dataset_id,
   month_label,
   value
) values ( 1,
           'March',
           40 );
insert into sales_overview_values (
   dataset_id,
   month_label,
   value
) values ( 1,
           'April',
           60 );
insert into sales_overview_values (
   dataset_id,
   month_label,
   value
) values ( 2,
           'January',
           20 );
insert into sales_overview_values (
   dataset_id,
   month_label,
   value
) values ( 2,
           'February',
           40 );
insert into sales_overview_values (
   dataset_id,
   month_label,
   value
) values ( 2,
           'March',
           30 );
insert into sales_overview_values (
   dataset_id,
   month_label,
   value
) values ( 2,
           'April',
           50 );

create table recent_activity (
   activity_key varchar2(100) primary key
);

insert into recent_activity ( activity_key ) values ( 'label:user_signed_up' );
insert into recent_activity ( activity_key ) values ( 'label:new_order' );
insert into recent_activity ( activity_key ) values ( 'label:payment_received' );
insert into recent_activity ( activity_key ) values ( 'label:product_added' );
insert into recent_activity ( activity_key ) values ( 'label:product_updated' );
insert into recent_activity ( activity_key ) values ( 'label:product_deleted' );

select *
  from recent_activity;

commit;